version: '3.7'

services:

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: ./dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true


  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    volumes:
      - tts-models:/backend/tts_models
volumes:
  tts-models:


  
