version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - tts-models:/backend/tts_models
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]

volumes:
  tts-models:
