# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /backend

# Copy the current directory contents into the container
COPY . /backend/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Install additional dependencies for audio processing
RUN apt-get update && apt-get install -y libsndfile1
RUN apt-get -y update && apt-get -y upgrade && apt-get install -y ffmpeg

# Expose the port that Uvicorn will listen on
EXPOSE 8000

# Define the command to run your application using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
