# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /backend

# Copy the current directory contents into the container at /app
COPY . /backend/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt  # If you have a requirements file

# Expose the port that Uvicorn will listen on
EXPOSE 8000

# Install the required shared library
RUN apt-get update && apt-get install -y libsndfile1

# Define the command to run your application using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
